"""add_push_subscriptions_table

Revision ID: 3aaf73508a03
Revises: 9ceb52332f7c
Create Date: 2026-02-11 19:04:09.690103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf73508a03'
down_revision: Union[str, Sequence[str], None] = '9ceb52332f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_address'], ['users.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_address'), ['user_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_address'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
