"""add group channels

Revision ID: 9ceb52332f7c
Revises: cb9a5a04695e
Create Date: 2026-02-11 12:16:20.079647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ceb52332f7c'
down_revision: Union[str, Sequence[str], None] = 'cb9a5a04695e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_address'], ['users.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['group_channels.id'], ),
    sa.ForeignKeyConstraint(['user_address'], ['users.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_id'), ['id'], unique=False)

    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['group_channels.id'], ),
    sa.ForeignKeyConstraint(['sender_address'], ['users.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_sender_address'), ['sender_address'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_sender_address'))
        batch_op.drop_index(batch_op.f('ix_group_messages_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_group_messages_channel_id'))

    op.drop_table('group_messages')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_channel_id'))

    op.drop_table('group_members')
    op.drop_table('group_channels')
    # ### end Alembic commands ###
